# Generated by Django 4.2.1 on 2023-06-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=3)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('email_institucional', models.EmailField(max_length=254)),
                ('email_pessoal', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('data_admissao', models.DateField()),
                ('data_rescisao', models.DateField(blank=True, null=True)),
                ('contatos_emergencia', models.TextField()),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='')),
                ('url_fotografia', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], default='ATIVO', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Colaborador',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=2, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='UnidadeJudiciaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Unidade Judiciária',
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('regiao', models.CharField(max_length=50, unique=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
            options={
                'verbose_name_plural': 'Tribunal',
            },
        ),
        migrations.CreateModel(
            name='Nicho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tribunal')),
                ('unidade_judiciaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidadejudiciaria')),
            ],
            options={
                'verbose_name_plural': 'Nicho',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('identificador', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('municipio_uf', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('nicho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nicho')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidadejudiciaria')),
            ],
        ),
    ]
