# Generated by Django 4.2.1 on 2023-06-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='fotografia',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='url_fotografia',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='contatos_emergencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
