# Generated by Django 4.2.1 on 2023-06-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_colaborador_fotografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='data_rescisao',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
